kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: multi-node-cluster # Custom cluster name (helps when using multiple clusters)
nodes:
  - role: control-plane
    image: kindest/node:v1.33.0 # Kubernetes version used for control-plane
  - role: worker
    image: kindest/node:v1.33.0 # Kubernetes version used for worker node 1
  - role: worker
    image: kindest/node:v1.33.0 # Kubernetes version used for worker node 2